# embeddings_path: "andersonbcdefg/bge-small-4096"
embeddings_path: "BAAI/bge-large-en-v1.5"
  
ctransformers:
  model_path: "./model/orcamaid-v3-13b-32k.Q2_K.gguf"

  model_type: "orcamaid"
  model_config: 
    'max_new_tokens' : 256
    'temperature' : 0
    'context_length' : 2048
    'gpu_layers' : 1
  